FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container

COPY . .

# Set environment variable for Flask 
ENV FLASK_APP=app.py

# Expose the port that Gunicorn will listen on
EXPOSE 5000


CMD ["gunicorn", "-w", "1", "-k", "eventlet", "--bind", "0.0.0.0:5000", "app:app"]